ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "address" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "postalCode" TEXT NOT NULL DEFAULT '';

ALTER TABLE "StoreProfile"
  ADD COLUMN IF NOT EXISTS "serviceScopes" TEXT NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "vehicleSizes" TEXT NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "productTypes" TEXT NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "itemConditions" TEXT NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "contactEmail" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "socialLinks" TEXT NOT NULL DEFAULT '{}';
